MPPA - Added Pmull -> now able to run the sort test

diff --git a/test/mppa/sort/Makefile b/test/mppa/sort/Makefile
--- a/test/mppa/sort/Makefile
+++ b/test/mppa/sort/Makefile
@@ -35,9 +35,9 @@ check: check-x86 check-k1c
 .PHONY:
 compc-check: test-ccomp
 	@if ! k1-cluster -- ./$<; then\
-		>&2 echo "ERROR k1c: $< failed";\
+		>&2 echo "ERROR k1c: sort $< failed";\
 	else\
-		echo "k1c: Test $< succeeded";\
+		echo "k1c: Test sort $< succeeded";\
 	fi
 
 .PHONY:
