Changed mmult to avoid recomputing + fixed potential source of bug in instr

diff --git a/test/mppa/mmult/Makefile b/test/mppa/mmult/Makefile
--- a/test/mppa/mmult/Makefile
+++ b/test/mppa/mmult/Makefile
@@ -2,49 +2,66 @@ K1CC ?= k1-mbr-gcc
 CC ?= gcc
 CCOMP ?= ccomp
 CFLAGS ?= -O2
+SIMU ?= k1-cluster
+TIMEOUT ?= 10s
+
+K1CCPATH=$(shell which $(K1CC))
+CCPATH=$(shell which $(CC))
+CCOMPPATH=$(shell which $(CCOMP))
+SIMUPATH=$(shell which $(SIMU))
 
 PRNG=../prng/prng.c
 
-ALL= mmult-test-gcc-x86 mmult-test-gcc-k1c mmult-test-ccomp-k1c\
+ALL= mmult-test-gcc-x86 mmult-test-gcc-k1c mmult-test-ccomp-k1c
+CCOMP_OUT= mmult-test-ccomp-k1c.out
+GCC_OUT= mmult-test-gcc-k1c.out
+X86_GCC_OUT= mmult-test-gcc-x86.out
+STUB_OUT=.zero
 
 all: $(ALL)
 
-mmult-test-gcc-x86: mmult.c $(PRNG)
+mmult-test-gcc-x86: mmult.c $(PRNG) $(CCPATH)
 	$(CC) $(CFLAGS) $^ -o $@
 
-mmult-test-gcc-k1c: mmult.c $(PRNG)
+mmult-test-gcc-k1c: mmult.c $(PRNG) $(K1CCPATH)
 	$(K1CC) $(CFLAGS) $^ -o $@
 
-mmult-test-ccomp-k1c: mmult.c $(PRNG)
+mmult-test-ccomp-k1c: mmult.c $(PRNG) $(CCOMPPATH)
 	$(CCOMP) $(CFLAGS) $^ -o $@
+
+.SECONDARY:
+%k1c.out: %k1c $(SIMUPATH)
+	ret=0; timeout $(TIMEOUT) $(SIMU) -- $< || { ret=$$?; } > $@; echo $$ret >> $@
+
+%x86.out: %x86
+	ret=0; timeout $(TIMEOUT) ./$< || { ret=$$?; } > $@; echo $$ret >> $@
+
+.zero:
+	@echo "0" > $@
 
 .PHONY:
 test: test-x86 test-k1c
 
 .PHONY:
-test-x86: mmult-test-gcc-x86
-	@if ! ./$<; then\
+test-x86: $(X86_GCC_OUT) $(STUB_OUT)
+	@if ! diff $< $(STUB_OUT); then\
 		>&2 echo "ERROR x86: $< failed";\
 	else\
-		echo "x86: Test $< succeeded";\
+		echo "GOOD x86: $< succeeded";\
 	fi
 
 .PHONY:
-test-k1c: mmult-test-gcc-k1c
-	@if ! k1-cluster -- ./$<; then\
+test-k1c: $(GCC_OUT) $(STUB_OUT)
+	@if ! diff $< $(STUB_OUT); then\
 		>&2 echo "ERROR k1c: $< failed";\
 	else\
-		echo "k1c: Test $< succeeded";\
+		echo "GOOD k1c: $< succeeded";\
 	fi
 
 .PHONY:
-check: mmult-test-ccomp-k1c
-	@if ! k1-cluster -- ./$<; then\
-		>&2 echo "ERROR k1c: mmult $< failed";\
+check: $(CCOMP_OUT) $(STUB_OUT)
+	@if ! diff $< $(STUB_OUT); then\
+		>&2 echo "ERROR k1c: $< failed";\
 	else\
-		echo "k1c: Test mmult $< succeeded";\
+		echo "GOOD k1c: $< succeeded";\
 	fi
-
-.PHONY:
-clean:
-	rm -f $(ALL)
