k1c -> kvx changes

diff --git a/test/mppa/mmult/Makefile b/test/mppa/mmult/Makefile
--- a/test/mppa/mmult/Makefile
+++ b/test/mppa/mmult/Makefile
@@ -1,20 +1,20 @@
-K1CC ?= k1-cos-gcc
+KVXC ?= k1-cos-gcc
 CC ?= gcc
 CCOMP ?= ccomp
 CFLAGS ?= -O2
 SIMU ?= k1-mppa
 TIMEOUT ?= 10s
 
-K1CCPATH=$(shell which $(K1CC))
+KVXCPATH=$(shell which $(KVXC))
 CCPATH=$(shell which $(CC))
 CCOMPPATH=$(shell which $(CCOMP))
 SIMUPATH=$(shell which $(SIMU))
 
 PRNG=../prng/prng.c
 
-ALL= mmult-test-gcc-x86 mmult-test-gcc-k1c mmult-test-ccomp-k1c
-CCOMP_OUT= mmult-test-ccomp-k1c.out
-GCC_OUT= mmult-test-gcc-k1c.out
+ALL= mmult-test-gcc-x86 mmult-test-gcc-kvx mmult-test-ccomp-kvx
+CCOMP_OUT= mmult-test-ccomp-kvx.out
+GCC_OUT= mmult-test-gcc-kvx.out
 X86_GCC_OUT= mmult-test-gcc-x86.out
 STUB_OUT=.zero
 
@@ -23,14 +23,14 @@ all: $(ALL)
 mmult-test-gcc-x86: mmult.c $(PRNG) $(CCPATH)
 	$(CC) $(CFLAGS) $(filter-out $(CCPATH),$^) -o $@
 
-mmult-test-gcc-k1c: mmult.c $(PRNG) $(K1CCPATH)
-	$(K1CC) $(CFLAGS) $(filter-out $(K1CCPATH),$^) -o $@
+mmult-test-gcc-kvx: mmult.c $(PRNG) $(KVXCPATH)
+	$(KVXC) $(CFLAGS) $(filter-out $(KVXCPATH),$^) -o $@
 
-mmult-test-ccomp-k1c: mmult.c $(PRNG) $(CCOMPPATH)
+mmult-test-ccomp-kvx: mmult.c $(PRNG) $(CCOMPPATH)
 	$(CCOMP) $(CFLAGS) $(filter-out $(CCOMPPATH),$^) -o $@
 
 .SECONDARY:
-%k1c.out: %k1c $(SIMUPATH)
+%kvx.out: %kvx $(SIMUPATH)
 	ret=0; timeout $(TIMEOUT) $(SIMU) -- $< > $@ || { ret=$$?; }; echo $$ret >> $@
 
 %x86.out: %x86
@@ -40,7 +40,7 @@ mmult-test-ccomp-k1c: mmult.c $(PRNG) $(CCOMPPATH)
 	@echo "0" > $@
 
 .PHONY:
-test: test-x86 test-k1c
+test: test-x86 test-kvx
 
 .PHONY:
 test-x86: $(X86_GCC_OUT) $(STUB_OUT)
@@ -51,17 +51,17 @@ test-x86: $(X86_GCC_OUT) $(STUB_OUT)
 	fi
 
 .PHONY:
-test-k1c: $(GCC_OUT) $(STUB_OUT)
+test-kvx: $(GCC_OUT) $(STUB_OUT)
 	@if ! diff $< $(STUB_OUT); then\
-		>&2 echo "ERROR k1c: $< failed";\
+		>&2 echo "ERROR kvx: $< failed";\
 	else\
-		echo "GOOD k1c: $< succeeded";\
+		echo "GOOD kvx: $< succeeded";\
 	fi
 
 .PHONY:
 check: $(CCOMP_OUT) $(STUB_OUT)
 	@if ! diff $< $(STUB_OUT); then\
-		>&2 echo "ERROR k1c: $< failed";\
+		>&2 echo "ERROR kvx: $< failed";\
 	else\
-		echo "GOOD k1c: $< succeeded";\
+		echo "GOOD kvx: $< succeeded";\
 	fi
diff --git a/test/mppa/prng/Makefile b/test/mppa/prng/Makefile
--- a/test/mppa/prng/Makefile
+++ b/test/mppa/prng/Makefile
@@ -1,18 +1,18 @@
-K1CC ?= k1-cos-gcc
+KVXC ?= k1-cos-gcc
 CC ?= gcc
 CCOMP ?= ccomp
 CFLAGS ?= -O2
 SIMU ?= k1-mppa
 TIMEOUT ?= 10s
 
-K1CCPATH=$(shell which $(K1CC))
+KVXCPATH=$(shell which $(KVXC))
 CCPATH=$(shell which $(CC))
 CCOMPPATH=$(shell which $(CCOMP))
 SIMUPATH=$(shell which $(SIMU))
 
-ALL= prng-test-gcc-x86 prng-test-gcc-k1c prng-test-ccomp-k1c
-CCOMP_OUT= prng-test-ccomp-k1c.out
-GCC_OUT= prng-test-gcc-k1c.out
+ALL= prng-test-gcc-x86 prng-test-gcc-kvx prng-test-ccomp-kvx
+CCOMP_OUT= prng-test-ccomp-kvx.out
+GCC_OUT= prng-test-gcc-kvx.out
 X86_GCC_OUT= prng-test-gcc-x86.out
 STUB_OUT=.zero
 
@@ -21,14 +21,14 @@ all: $(ALL)
 prng-test-gcc-x86: prng.c $(CCPATH)
 	$(CC) -D__UNIT_TEST_PRNG__ $(CFLAGS) $< -o $@
 
-prng-test-gcc-k1c: prng.c $(K1CCPATH)
-	$(K1CC) -D__UNIT_TEST_PRNG__ $(CFLAGS) $< -o $@
+prng-test-gcc-kvx: prng.c $(KVXCPATH)
+	$(KVXC) -D__UNIT_TEST_PRNG__ $(CFLAGS) $< -o $@
 
-prng-test-ccomp-k1c: prng.c $(CCOMPPATH)
+prng-test-ccomp-kvx: prng.c $(CCOMPPATH)
 	$(CCOMP) -D__UNIT_TEST_PRNG__ $(CFLAGS) $< -o $@
 
 .SECONDARY:
-%k1c.out: %k1c $(SIMUPATH)
+%kvx.out: %kvx $(SIMUPATH)
 	ret=0; timeout $(TIMEOUT) $(SIMU) -- $<  > $@ || { ret=$$?; }; echo $$ret >> $@
 
 %x86.out: %x86
@@ -38,7 +38,7 @@ prng-test-ccomp-k1c: prng.c $(CCOMPPATH)
 	@echo "0" > $@
 
 .PHONY:
-test: test-x86 test-k1c
+test: test-x86 test-kvx
 
 .PHONY:
 test-x86: $(X86_GCC_OUT) $(STUB_OUT)
@@ -49,21 +49,21 @@ test-x86: $(X86_GCC_OUT) $(STUB_OUT)
 	fi
 
 .PHONY:
-test-k1c: $(GCC_OUT) $(STUB_OUT)
+test-kvx: $(GCC_OUT) $(STUB_OUT)
 	@if ! diff $< $(STUB_OUT); then\
-		>&2 echo "ERROR k1c: $< failed";\
+		>&2 echo "ERROR kvx: $< failed";\
 	else\
-		echo "GOOD k1c: $< succeeded";\
+		echo "GOOD kvx: $< succeeded";\
 	fi
 
 .PHONY:
 check: $(CCOMP_OUT) $(STUB_OUT)
 	@if ! diff $< $(STUB_OUT); then\
-		>&2 echo "ERROR k1c: $< failed";\
+		>&2 echo "ERROR kvx: $< failed";\
 	else\
-		echo "GOOD k1c: $< succeeded";\
+		echo "GOOD kvx: $< succeeded";\
 	fi
 
 .PHONY:
 clean:
-	rm -f prng-test-gcc-x86 prng-test-gcc-k1c prng-test-ccomp-k1c
+	rm -f prng-test-gcc-x86 prng-test-gcc-kvx prng-test-ccomp-kvx
diff --git a/test/mppa/sort/Makefile b/test/mppa/sort/Makefile
--- a/test/mppa/sort/Makefile
+++ b/test/mppa/sort/Makefile
@@ -1,11 +1,11 @@
-K1CC ?= k1-cos-gcc
+KVXC ?= k1-cos-gcc
 CC ?= gcc
 CCOMP ?= ccomp
 CFLAGS ?= -O2
 SIMU ?= k1-mppa
 TIMEOUT ?= 10s
 
-K1CCPATH=$(shell which $(K1CC))
+KVXCPATH=$(shell which $(KVXC))
 CCPATH=$(shell which $(CC))
 CCOMPPATH=$(shell which $(CCOMP))
 SIMUPATH=$(shell which $(SIMU))
@@ -14,15 +14,15 @@ PRNG=../prng/prng.c
 
 CFILES=insertion.c merge.c selection.c main.c
 
-ALL= insertion-gcc-x86 insertion-gcc-k1c insertion-ccomp-k1c\
-     selection-gcc-x86 selection-gcc-k1c selection-ccomp-k1c\
-     merge-gcc-x86 merge-gcc-k1c merge-ccomp-k1c\
-     main-gcc-x86 main-gcc-k1c main-ccomp-k1c
+ALL= insertion-gcc-x86 insertion-gcc-kvx insertion-ccomp-kvx\
+     selection-gcc-x86 selection-gcc-kvx selection-ccomp-kvx\
+     merge-gcc-x86 merge-gcc-kvx merge-ccomp-kvx\
+     main-gcc-x86 main-gcc-kvx main-ccomp-kvx
 
-CCOMP_OUT= insertion-ccomp-k1c.out selection-ccomp-k1c.out merge-ccomp-k1c.out\
-		   main-ccomp-k1c.out
-GCC_OUT= insertion-gcc-k1c.out selection-gcc-k1c.out merge-gcc-k1c.out\
-		   main-gcc-k1c.out
+CCOMP_OUT= insertion-ccomp-kvx.out selection-ccomp-kvx.out merge-ccomp-kvx.out\
+		   main-ccomp-kvx.out
+GCC_OUT= insertion-gcc-kvx.out selection-gcc-kvx.out merge-gcc-kvx.out\
+		   main-gcc-kvx.out
 X86_GCC_OUT= insertion-gcc-x86.out selection-gcc-x86.out merge-gcc-x86.out\
 		   main-gcc-x86.out
 STUB_OUT= .zero
@@ -35,23 +35,23 @@ main-gcc-x86: $(CFILES) $(PRNG) $(CCPATH)
 %-gcc-x86: %.c $(PRNG) $(CCPATH)
 	$(CC) -D__UNIT_TEST_$$(echo $(basename $<) | tr a-z A-Z)__ $(CFLAGS) $(filter-out $(CCPATH),$^) -o $@
 
-main-gcc-k1c: $(CFILES) $(PRNG) $(CCPATH)
-	$(K1CC) $(CFLAGS) $(filter-out $(CCPATH),$^) -o $@
+main-gcc-kvx: $(CFILES) $(PRNG) $(CCPATH)
+	$(KVXC) $(CFLAGS) $(filter-out $(CCPATH),$^) -o $@
 
-%-gcc-k1c: %.c $(PRNG) $(K1CCPATH)
-	$(K1CC) -D__UNIT_TEST_$$(echo $(basename $<) | tr a-z A-Z)__ $(CFLAGS) $(filter-out $(K1CCPATH),$^) -o $@
+%-gcc-kvx: %.c $(PRNG) $(KVXCPATH)
+	$(KVXC) -D__UNIT_TEST_$$(echo $(basename $<) | tr a-z A-Z)__ $(CFLAGS) $(filter-out $(KVXCPATH),$^) -o $@
 
-main-ccomp-k1c: $(CFILES) $(PRNG) $(CCOMPPATH)
+main-ccomp-kvx: $(CFILES) $(PRNG) $(CCOMPPATH)
 	$(CCOMP) $(CFLAGS) $(filter-out $(CCOMPPATH),$^) -o $@
 
-%-ccomp-k1c: %.c $(PRNG) $(CCOMPPATH)
+%-ccomp-kvx: %.c $(PRNG) $(CCOMPPATH)
 	$(CCOMP) -D__UNIT_TEST_$$(echo $(basename $<) | tr a-z A-Z)__ $(CFLAGS) $(filter-out $(CCOMPPATH),$^) -o $@
 
 .SECONDARY:
 %x86.out: %x86
 	ret=0; timeout $(TIMEOUT) ./$< > $@ || { ret=$$?; }; echo $$ret >> $@
 
-%k1c.out: %k1c $(SIMUPATH)
+%kvx.out: %kvx $(SIMUPATH)
 	ret=0; timeout $(TIMEOUT) $(SIMU) -- $< > $@ || { ret=$$?; }; echo $$ret >> $@
 
 .zero:
@@ -68,24 +68,24 @@ test-x86: $(STUB_OUT) $(X86_GCC_OUT)
 	done
 
 .PHONY:
-test-k1c: $(STUB_OUT) $(GCC_OUT)
+test-kvx: $(STUB_OUT) $(GCC_OUT)
 	@for test in $(wordlist 2,100,$^); do\
 		if ! diff $$test $(STUB_OUT); then\
-			>&2 echo "ERROR k1c: $$test failed";\
+			>&2 echo "ERROR kvx: $$test failed";\
 		else\
-			echo "GOOD k1c: $$test succeeded";\
+			echo "GOOD kvx: $$test succeeded";\
 		fi;\
 	done
 
 .PHONY:
-test: test-x86 test-k1c
+test: test-x86 test-kvx
 
 .PHONY:
 check: $(STUB_OUT) $(CCOMP_OUT)
 	@for test in $(wordlist 2,100,$^); do\
 		if ! diff $$test $(STUB_OUT); then\
-			>&2 echo "ERROR k1c: $$test failed";\
+			>&2 echo "ERROR kvx: $$test failed";\
 		else\
-			echo "GOOD k1c: $$test succeeded";\
+			echo "GOOD kvx: $$test succeeded";\
 		fi;\
 	done
